"""Pool de 100 usuarios de prueba para el Dev Tools Panel.

Uso:
    from backend.src.core.dev_users_pool import get_random_users
    users = get_random_users(10)
"""

from __future__ import annotations

import random

_POOL: list[dict] = [
    {"nombre": "Ana García",         "instagram": "anagarcia_test",       "telefono": "+34611000001", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Carlos López",       "instagram": "carloslopez_test",     "telefono": "+34611000002", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "María Fernández",    "instagram": "mariafernandez_test",  "telefono": "+34611000003", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Pedro Martínez",     "instagram": "pedromartinez_test",   "telefono": "+34611000004", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Laura Sánchez",      "instagram": "laurasanchez_test",    "telefono": "+34611000005", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Juan González",      "instagram": "juangonzalez_test",    "telefono": "+34611000006", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Elena Torres",       "instagram": "elenatorres_test",     "telefono": "+34611000007", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Miguel Ruiz",        "instagram": "miguelruiz_test",      "telefono": "+34611000008", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Sofía Moreno",       "instagram": "sofiamoreno_test",     "telefono": "+34611000009", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "David Jiménez",      "instagram": "davidjimenez_test",    "telefono": "+34611000010", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Carmen Díaz",        "instagram": "carmendi_az_test",     "telefono": "+34611000011", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Rafael Molina",      "instagram": "rafaelmolina_test",    "telefono": "+34611000012", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Patricia Romero",    "instagram": "patriciaromero_test",  "telefono": "+34611000013", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Alberto Serrano",    "instagram": "albertoserrano_test",  "telefono": "+34611000014", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Isabel Navarro",     "instagram": "isabelnavarro_test",   "telefono": "+34611000015", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Sergio Blanco",      "instagram": "sergioblanco_test",    "telefono": "+34611000016", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Lucía Castillo",     "instagram": "luciacastillo_test",   "telefono": "+34611000017", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Fernando Vega",      "instagram": "fernandovega_test",    "telefono": "+34611000018", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Marta Ramos",        "instagram": "martaramos_test",      "telefono": "+34611000019", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Andrés Suárez",      "instagram": "andressuarez_test",    "telefono": "+34611000020", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Beatriz Herrero",    "instagram": "beatrizherrero_test",  "telefono": "+34611000021", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Ricardo Medina",     "instagram": "ricardomedina_test",   "telefono": "+34611000022", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Natalia Guerrero",   "instagram": "nataliaguerrero_test", "telefono": "+34611000023", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Javier Cano",        "instagram": "javiercano_test",      "telefono": "+34611000024", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Cristina Aguilar",   "instagram": "cristinaaguilar_test", "telefono": "+34611000025", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Pablo Domínguez",    "instagram": "pablodm_test",         "telefono": "+34611000026", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Rosa León",          "instagram": "rosaleon_test",        "telefono": "+34611000027", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Alejandro Mora",     "instagram": "alejandromora_test",   "telefono": "+34611000028", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Teresa Delgado",     "instagram": "teresadelgado_test",   "telefono": "+34611000029", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Óscar Vargas",       "instagram": "oscarvargas_test",     "telefono": "+34611000030", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Nuria Pascual",      "instagram": "nuriapascual_test",    "telefono": "+34611000031", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Mario Cabrera",      "instagram": "mariocabrera_test",    "telefono": "+34611000032", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Verónica Iglesias",  "instagram": "veronicaiglesias_test","telefono": "+34611000033", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Francisco Peña",     "instagram": "franciscopena_test",   "telefono": "+34611000034", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Silvia Cortés",      "instagram": "silviacortes_test",    "telefono": "+34611000035", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Daniel Fuentes",     "instagram": "danielfuentes_test",   "telefono": "+34611000036", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Raquel Reyes",       "instagram": "raquelreyes_test",     "telefono": "+34611000037", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Iván Flores",        "instagram": "ivanflores_test",      "telefono": "+34611000038", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Pilar Ortega",       "instagram": "pilarortega_test",     "telefono": "+34611000039", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Rubén Santos",       "instagram": "rubensantos_test",     "telefono": "+34611000040", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Alicia Muñoz",       "instagram": "aliciamuoz_test",      "telefono": "+34611000041", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Jorge Bravo",        "instagram": "jorgebravo_test",      "telefono": "+34611000042", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Vanesa Gil",         "instagram": "vanesagil_test",       "telefono": "+34611000043", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Enrique Prieto",     "instagram": "enriqueprieto_test",   "telefono": "+34611000044", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Miriam Cruz",        "instagram": "miriamcruz_test",      "telefono": "+34611000045", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Gonzalo Méndez",     "instagram": "gonzalomendez_test",   "telefono": "+34611000046", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Sandra Ibáñez",      "instagram": "sandraibez_test",      "telefono": "+34611000047", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Antonio Lozano",     "instagram": "antoniolozano_test",   "telefono": "+34611000048", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Rebeca Campos",      "instagram": "rebecacampos_test",    "telefono": "+34611000049", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Guillermo Pereira",  "instagram": "guillermopereira_test","telefono": "+34611000050", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Lorena Gallego",     "instagram": "lorenagallego_test",   "telefono": "+34611000051", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Víctor Alonso",      "instagram": "victoralonso_test",    "telefono": "+34611000052", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Susana Marín",       "instagram": "susanamarin_test",     "telefono": "+34611000053", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Hugo Carrasco",      "instagram": "hugocarrasco_test",    "telefono": "+34611000054", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Mónica Vidal",       "instagram": "monicavidal_test",     "telefono": "+34611000055", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Adrián Parra",       "instagram": "adrianparra_test",     "telefono": "+34611000056", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Noelia Soto",        "instagram": "noeliaosto_test",      "telefono": "+34611000057", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "César Ríos",         "instagram": "cesarios_test",        "telefono": "+34611000058", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Yolanda Montes",     "instagram": "yolandamontes_test",   "telefono": "+34611000059", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Héctor Crespo",      "instagram": "hectorcrespo_test",    "telefono": "+34611000060", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Amparo Rubio",       "instagram": "amparorubio_test",     "telefono": "+34611000061", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Emilio Nieto",       "instagram": "emilonieto_test",      "telefono": "+34611000062", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Consuelo Vega",      "instagram": "consuelovega_test",    "telefono": "+34611000063", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Rodrigo Salas",      "instagram": "rodrigosalas_test",    "telefono": "+34611000064", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Inmaculada Vera",    "instagram": "inmaveara_test",       "telefono": "+34611000065", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Tomás Guerrero",     "instagram": "tomasguerrero_test",   "telefono": "+34611000066", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Almudena Peñas",     "instagram": "almudenap_test",       "telefono": "+34611000067", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Ignacio Moya",       "instagram": "ignaciomoya_test",     "telefono": "+34611000068", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Dolores Calvo",      "instagram": "dolorescalvo_test",    "telefono": "+34611000069", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Arturo Herrera",     "instagram": "arturoherrera_test",   "telefono": "+34611000070", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Esperanza Mora",     "instagram": "esperanzamora_test",   "telefono": "+34611000071", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Manuel Hidalgo",     "instagram": "manuelhidalgo_test",   "telefono": "+34611000072", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Paloma Iglesias",    "instagram": "palomaiglesias_test",  "telefono": "+34611000073", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Álvaro Rivas",       "instagram": "alvarorivas_test",     "telefono": "+34611000074", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Graciela Pinto",     "instagram": "gracielapinto_test",   "telefono": "+34611000075", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Ramón Téllez",       "instagram": "ramontellez_test",     "telefono": "+34611000076", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Lourdes Bernal",     "instagram": "lourdesbernal_test",   "telefono": "+34611000077", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Agustín Leal",       "instagram": "agustinleal_test",     "telefono": "+34611000078", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Margarita Cano",     "instagram": "margaritacano_test",   "telefono": "+34611000079", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Esteban Varela",     "instagram": "estebanvarela_test",   "telefono": "+34611000080", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Concepción Rueda",   "instagram": "conceprueda_test",     "telefono": "+34611000081", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Xavier Ferrer",      "instagram": "xavierferrer_test",    "telefono": "+34611000082", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Ainhoa Eguia",       "instagram": "ainhoaeguia_test",     "telefono": "+34611000083", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Mikel Etxeberria",   "instagram": "mikeletxe_test",       "telefono": "+34611000084", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Itziar Goikoetxea",  "instagram": "itziargoiko_test",     "telefono": "+34611000085", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Unai Zabala",        "instagram": "unaizabala_test",      "telefono": "+34611000086", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Leire Arostegi",     "instagram": "leirearostegi_test",   "telefono": "+34611000087", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Oriol Puig",         "instagram": "oriolpuig_test",       "telefono": "+34611000088", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Montserrat Bosch",   "instagram": "montserratbosch_test", "telefono": "+34611000089", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Ferran Castellà",    "instagram": "ferrancastella_test",  "telefono": "+34611000090", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
    {"nombre": "Laia Valls",         "instagram": "laiavalls_test",       "telefono": "+34611000091", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "instagram"},
    {"nombre": "Txema Zubiaurre",    "instagram": "txemazubi_test",       "telefono": "+34611000092", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "referido"},
    {"nombre": "Amaia Urrutia",      "instagram": "amaiaurrutia_test",    "telefono": "+34611000093", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Ander Mendikute",    "instagram": "andermendi_test",      "telefono": "+34611000094", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "amigos"},
    {"nombre": "Nekane Larrea",      "instagram": "nekanelarrea_test",    "telefono": "+34611000095", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "cartel"},
    {"nombre": "Joseba Arrizabalaga","instagram": "josebaarri_test",      "telefono": "+34611000096", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "instagram"},
    {"nombre": "Edurne Azpeitia",    "instagram": "edurneazpeitia_test",  "telefono": "+34611000097", "experiencia_raw": "Es mi primera vez",                  "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "referido"},
    {"nombre": "Gorka Etxeandia",    "instagram": "gorkaetxe_test",       "telefono": "+34611000098", "experiencia_raw": "He probado alguna vez",              "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "whatsapp"},
    {"nombre": "Maite Zubizarreta",  "instagram": "maitezubi_test",       "telefono": "+34611000099", "experiencia_raw": "Llevo tiempo haciendo stand-up",     "disponibilidad_ultimo_minuto": "No",  "origen_conocimiento": "amigos"},
    {"nombre": "Xabier Olano",       "instagram": "xabierolano_test",     "telefono": "+34611000100", "experiencia_raw": "Soy un profesional / tengo cachés", "disponibilidad_ultimo_minuto": "Sí",  "origen_conocimiento": "cartel"},
]

assert len(_POOL) == 100, f"El pool debe tener 100 usuarios, tiene {len(_POOL)}"


def get_random_users(n: int) -> list[dict]:
    """Devuelve n usuarios aleatorios sin repetición del pool de 100."""
    if n > len(_POOL):
        raise ValueError(f"No se pueden pedir más de {len(_POOL)} usuarios")
    return random.sample(_POOL, n)
